
import = [
    "~/.config/alacritty/themes/themes/tango_dark.toml"
]

[env]
TERM = "alacritty-direct"

[window]
dimensions.columns = 140
dimensions.lines = 50

resize_increments = true

[font]
size = 8.5

normal.family = "Liberation Mono"
bold.family = "Liberation Mono"
italic.family = "Liberation Mono"
bold_italic.family = "Liberation Mono"

# normal.family = "Incosolata Nerd Font"
# bold.family = "Incosolata Nerd Font"
# italic.family = "Incosolata Nerd Font"
# bold_italic.family = "Incosolata Nerd Font"

# normal.family = "FreeMono"
# bold.family = "FreeMono"
# italic.family = "FreeMono"
# bold_italic.family = "FreeMono"

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "F11", action = "ToggleFullscreen" },
]

