
# bind y run-shell "tmux show-buffer > /srv/samba/anonymous_shares/tmux.clip"
bind y run-shell "tmux show-buffer | xsel -i -b"
bind '"' split-window -v -c '#{pane_current_path}'  # Split panes horizontal
bind % split-window -h -c '#{pane_current_path}'  # Split panes vertically
bind c new-window -c '#{pane_current_path}' 

bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"

set -g mouse on
# set -g default-terminal "tmux-256color"
# set -g default-terminal "xterm-256color"
# set -g default-terminal "screen-256color"

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# set-option -g xterm-keys on

set-window-option -g mode-keys vi

set -g base-index 1
setw -g pane-base-index 1

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sessionist'

set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'

set -g @plugin 'fcsonline/tmux-thumbs'

run-shell ~/.tmux/plugins/tmux-thumbs/tmux-thumbs.tmux


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# pane border
# set -g status-style bg='#064e9a' # Синий
# set -g status-style bg='#8f2403' # Кирпичный
# set -g status-style bg='#00802d' # Зеленый
# set -g status-style bg='#800053' # Фиолетовый
# set -g status-style bg='#036e8f' # Голубой

